"""add path_vars to requests

Revision ID: fb4c3b2d2623
Revises: 4a7cb22f2985
Create Date: 2026-05-13 17:28:12.330497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb4c3b2d2623'
down_revision: Union[str, None] = '4a7cb22f2985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('path_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'path_vars')
    # ### end Alembic commands ###
